/* ── Pitch. shared data ──────────────────────────────────────────────────── */

window.PITCH_EVENTS = [
  {
    id: 'rundle-mall-night-eats',
    name: 'Rundle Mall Night Eats',
    category: 'Night Market',
    suburb: 'Adelaide CBD', state: 'SA',
    location: 'Rundle Mall, Adelaide CBD SA 5000',
    date: '2026-04-12',
    dateLabel: 'Sat 12 Apr 2026',
    dateLong: 'Saturday 12 April 2026',
    time: '5pm–10pm', timeLong: '5:00pm – 10:00pm',
    total: 20, filled: 14,
    feeMin: 200, feeMax: 350,
    deadline: '2026-04-05', deadlineLabel: '5 April 2026',
    stallSize: '3m × 3m (standard) · 3m × 6m available',
    power: true, water: false,
    setupTime: '2:00pm – 4:30pm', packdown: '10:00pm – 11:30pm',
    attendance: '5,000–7,000 visitors',
    emoji: '🌃',
    about: "Rundle Mall Night Eats is Adelaide's premier weekly night market, drawing 5,000+ visitors each Saturday evening to the heart of the CBD. Now in its 4th year, the event has become a fixture for foodies, families, and Adelaide's vibrant street food culture. Vendors operate from dedicated 3×3m booths along the pedestrianised mall, with high foot traffic from 5pm through to closing. The event is professionally run by Adelaide City Council Events with full security, waste management, and crowd facilitation provided.",
    organiser: { name: 'Adelaide City Council Events', initials: 'AC', events: 34, rating: 4.8 },
    vendorLineup: [
      { name: "Smoky Joe's BBQ", type: 'BBQ & Grill', initials: 'SJ', id: 'smoky-joes-bbq', color: '#E8500A' },
      { name: 'The Green Fold', type: 'Vegan', initials: 'TG', id: 'green-bowl', color: '#2D8B55' },
      { name: 'Barista Mob', type: 'Coffee & Drinks', initials: 'BM', id: 'beanery-coffee', color: '#2B5BA8' },
      { name: 'Taco Cartel', type: 'Mexican', initials: 'TC', id: 'taco-loco', color: '#C9840A' },
    ],
    feeIncludes: ['Standard 3×3m booth space', '15A power connection', 'Council food permit (included)', 'Waste bin allocation'],
    lookingFor: ['🌮 Street Food', '🍱 Asian Cuisine', '🥩 BBQ & Grill', '🍦 Desserts', '🍕 Pizza', '☕ Coffee & Drinks', '🌾 Vegan / Plant-based', '🥙 Middle Eastern'],
    lookingForPreferred: ['🌮 Street Food', '🍱 Asian Cuisine', '🥩 BBQ & Grill', '🍦 Desserts', '🥙 Middle Eastern'],
  },
  {
    id: 'showground-harvest-fair',
    name: 'Adelaide Showground Harvest Fair',
    category: 'Farmers Market',
    suburb: 'Wayville', state: 'SA',
    location: 'Adelaide Showground, Leader St, Wayville SA 5034',
    date: '2026-04-19',
    dateLabel: 'Sun 19 Apr 2026',
    dateLong: 'Sunday 19 April 2026',
    time: '8am–1pm', timeLong: '8:00am – 1:00pm',
    total: 20, filled: 18,
    feeMin: 150, feeMax: 280,
    deadline: '2026-04-06', deadlineLabel: '6 April 2026',
    stallSize: '3m × 3m standard',
    power: false, water: true,
    setupTime: '6:00am – 7:30am', packdown: '1:00pm – 2:30pm',
    attendance: '3,000–4,500 visitors',
    emoji: '🌾',
    about: 'The Adelaide Showground Harvest Fair celebrates South Australia\'s incredible produce and food culture in the iconic heritage surrounds of the Showground. This morning market draws a loyal crowd of food-lovers, families, and keen home cooks looking for the freshest local fare. Artisan producers, specialty food vendors, and street food operators all share space in a relaxed, community-driven atmosphere. Stallholders benefit from covered pavilion sections and a dedicated footfall from 8am.',
    organiser: { name: 'SA Showground Events', initials: 'SA', events: 18, rating: 4.7 },
    vendorLineup: [
      { name: 'Green Bowl', type: 'Vegan', initials: 'GB', id: 'green-bowl', color: '#2D8B55' },
      { name: 'Beanery Coffee Co.', type: 'Coffee', initials: 'BC', id: 'beanery-coffee', color: '#C9840A' },
      { name: 'Pressed & Brewed', type: 'Drinks', initials: 'PB', id: 'pressed-and-brewed', color: '#2B5BA8' },
    ],
    feeIncludes: ['3×3m stall space', 'Water access point nearby', 'Shared waste facilities', 'Event signage & map listing'],
    lookingFor: ['🌿 Artisan Produce', '🥞 Breakfast & Brunch', '☕ Coffee & Drinks', '🍞 Bakery', '🥗 Vegan / Healthy', '🍯 Local Honey & Preserves'],
    lookingForPreferred: ['🥞 Breakfast & Brunch', '☕ Coffee & Drinks', '🍞 Bakery', '🌿 Artisan Produce'],
  },
  {
    id: 'fringe-food-village',
    name: 'Fringe Food Village 2026',
    category: 'Festival',
    suburb: 'Adelaide CBD', state: 'SA',
    location: 'Rundle Park (Kadlitpina), East Terrace, Adelaide SA 5000',
    date: '2026-03-02', dateEnd: '2026-03-22',
    dateLabel: '2–22 Mar 2026',
    dateLong: '2 March – 22 March 2026',
    time: 'Various', timeLong: 'Wed–Sun from 5:00pm',
    total: 40, filled: 28,
    feeMin: 400, feeMax: 700,
    deadline: '2026-03-08', deadlineLabel: '8 March 2026',
    stallSize: '3m × 3m or 3m × 6m',
    power: true, water: true,
    setupTime: '12:00pm – 3:00pm (each day)', packdown: '12:00am – 1:30am',
    attendance: '8,000–15,000 visitors per night',
    emoji: '🎪',
    about: 'The Fringe Food Village is Adelaide Fringe Festival\'s dedicated street food precinct — one of the largest and most exciting food events in the southern hemisphere. Over 21 nights, vendors serve thousands of festival-goers exploring the Rundle Park hub. With live entertainment, bars, and art installations surrounding the food village, the atmosphere is electric and the foot traffic is unmatched. Multi-day trading means vendors can build a loyal following throughout the festival run.',
    organiser: { name: 'Adelaide Fringe Festival', initials: 'AF', events: 12, rating: 4.9 },
    vendorLineup: [
      { name: "Smoky Joe's BBQ", type: 'BBQ & Grill', initials: 'SJ', id: 'smoky-joes-bbq', color: '#E8500A' },
      { name: 'Taco Loco', type: 'Mexican', initials: 'TL', id: 'taco-loco', color: '#2D8B55' },
      { name: 'The Dessert Lab', type: 'Desserts', initials: 'DL', id: 'the-dessert-lab', color: '#C9840A' },
      { name: 'Wok & Roll', type: 'Asian Fusion', initials: 'WR', id: 'wok-and-roll', color: '#2B5BA8' },
    ],
    feeIncludes: ['Booth space (3×3m or 3×6m)', '15A power connection', 'Water access', 'Fringe marketing materials', 'Security & crowd management'],
    lookingFor: ['🌮 Street Food', '🍱 Asian Cuisine', '🍦 Desserts', '🍔 Burgers', '☕ Coffee & Drinks', '🥩 BBQ & Grill', '🍕 Pizza', '🌾 Vegan'],
    lookingForPreferred: ['🌮 Street Food', '🍱 Asian Cuisine', '🍦 Desserts', '🍔 Burgers'],
  },
  {
    id: 'barossa-food-wine',
    name: 'Barossa Valley Food & Wine',
    category: 'Festival',
    suburb: 'Tanunda', state: 'SA',
    location: 'Barossa Oval, Murray St, Tanunda SA 5352',
    date: '2026-04-26',
    dateLabel: 'Sun 26 Apr 2026',
    dateLong: 'Sunday 26 April 2026',
    time: '11am–5pm', timeLong: '11:00am – 5:00pm',
    total: 20, filled: 12,
    feeMin: 300, feeMax: 500,
    deadline: '2026-04-12', deadlineLabel: '12 April 2026',
    stallSize: '3m × 3m standard · 4m × 4m premium available',
    power: true, water: false,
    setupTime: '8:30am – 10:30am', packdown: '5:00pm – 7:00pm',
    attendance: '4,000–6,000 visitors',
    emoji: '🍷',
    about: 'Set against the breathtaking backdrop of the Barossa Valley, this annual food and wine celebration brings together premium regional vendors alongside the region\'s world-renowned wineries. Visitors travel from across Australia for the Barossa Valley Food & Wine festival — expect a discerning, high-spending crowd looking for quality produce, artisan street food, and unforgettable flavour experiences. This is the signature regional food event for South Australia.',
    organiser: { name: 'Barossa Valley Tourism', initials: 'BV', events: 8, rating: 4.9 },
    vendorLineup: [
      { name: 'Napoli Express', type: 'Italian', initials: 'NE', id: 'napoli-express', color: '#C9840A' },
      { name: 'Ocean & Fire', type: 'Seafood', initials: 'OF', id: 'ocean-and-fire', color: '#2B5BA8' },
      { name: 'The Dessert Lab', type: 'Desserts', initials: 'DL', id: 'the-dessert-lab', color: '#E8500A' },
    ],
    feeIncludes: ['3×3m or 4×4m stall space', '15A power access', 'Event program listing', 'Dedicated vendor parking'],
    lookingFor: ['🍷 Wine Pairing Food', '🧀 Artisan & Gourmet', '🫒 Mediterranean', '🍦 Premium Desserts', '☕ Specialty Coffee', '🥩 Premium Grill'],
    lookingForPreferred: ['🍷 Wine Pairing Food', '🧀 Artisan & Gourmet', '🍦 Premium Desserts'],
  },
  {
    id: 'glenelg-twilight',
    name: 'Glenelg Twilight Market',
    category: 'Twilight Market',
    suburb: 'Glenelg', state: 'SA',
    location: 'Moseley Square, Jetty Rd, Glenelg SA 5045',
    date: '2026-05-03',
    dateLabel: 'Sun 3 May 2026',
    dateLong: 'Sunday 3 May 2026',
    time: '4pm–9pm', timeLong: '4:00pm – 9:00pm',
    total: 20, filled: 16,
    feeMin: 120, feeMax: 200,
    deadline: '2026-04-19', deadlineLabel: '19 April 2026',
    stallSize: '3m × 3m standard',
    power: true, water: false,
    setupTime: '2:00pm – 3:30pm', packdown: '9:00pm – 10:30pm',
    attendance: '2,500–3,500 visitors',
    emoji: '🌅',
    about: 'The Glenelg Twilight Market is a beloved coastal community event set in Moseley Square, just steps from the famous Glenelg jetty and beach. As the sun sets over the Gulf St Vincent, locals and tourists fill the square for an evening of street food, artisan goods, and live music. The relaxed beach-town atmosphere attracts a diverse crowd of families, couples, and day-trippers who\'ve made the tram trip from the city. Vendor spots sell out quickly — the market has a waiting list each month.',
    organiser: { name: 'City of Holdfast Bay', initials: 'CH', events: 24, rating: 4.7 },
    vendorLineup: [
      { name: 'Ocean & Fire', type: 'Seafood', initials: 'OF', id: 'ocean-and-fire', color: '#2B5BA8' },
      { name: "Smoky Joe's BBQ", type: 'BBQ', initials: 'SJ', id: 'smoky-joes-bbq', color: '#E8500A' },
      { name: 'The Churro Stand', type: 'Desserts', initials: 'CS', id: 'the-churro-stand', color: '#C9840A' },
      { name: 'Beanery Coffee Co.', type: 'Coffee', initials: 'BC', id: 'beanery-coffee', color: '#2D8B55' },
    ],
    feeIncludes: ['3×3m booth space', 'Power connection', 'Council permits & insurance', 'Event map listing'],
    lookingFor: ['🦞 Seafood', '🌮 Street Food', '🍦 Desserts & Sweets', '☕ Coffee & Drinks', '🍔 Burgers', '🌾 Healthy & Vegan'],
    lookingForPreferred: ['🦞 Seafood', '🌮 Street Food', '🍦 Desserts & Sweets'],
  },
  {
    id: 'port-adelaide-night-market',
    name: 'Port Adelaide Night Market',
    category: 'Night Market',
    suburb: 'Port Adelaide', state: 'SA',
    location: 'Fisherman\'s Wharf, St Vincent St, Port Adelaide SA 5015',
    date: '2026-05-10',
    dateLabel: 'Sun 10 May 2026',
    dateLong: 'Sunday 10 May 2026',
    time: '5pm–10pm', timeLong: '5:00pm – 10:00pm',
    total: 20, filled: 9,
    feeMin: 150, feeMax: 250,
    deadline: '2026-04-26', deadlineLabel: '26 April 2026',
    stallSize: '3m × 3m standard',
    power: true, water: true,
    setupTime: '2:30pm – 4:30pm', packdown: '10:00pm – 11:30pm',
    attendance: '2,000–3,000 visitors',
    emoji: '🌊',
    about: 'Set on the historic Fisherman\'s Wharf precinct in Port Adelaide, this monthly night market celebrates the port\'s maritime heritage with a lively street food atmosphere. The surrounding heritage buildings and waterfront location give this market a unique character unlike any other in Adelaide. With ongoing revitalisation of the Port, foot traffic is growing year-on-year. Plenty of spots still available — this is a great opportunity for vendors looking to build a presence in an emerging area.',
    organiser: { name: 'Port Adelaide Enfield Council', initials: 'PA', events: 15, rating: 4.5 },
    vendorLineup: [
      { name: 'Brewski Burgers', type: 'Burgers', initials: 'BB', id: 'brewski-burgers', color: '#C9840A' },
      { name: 'Punjab Palace', type: 'Indian', initials: 'PP', id: 'punjab-palace', color: '#E8500A' },
    ],
    feeIncludes: ['3×3m booth space', '15A power & water access', 'Council food permit', 'Waste management'],
    lookingFor: ['🦞 Seafood', '🍔 Burgers & Street Food', '🌮 World Cuisine', '☕ Coffee & Drinks', '🍦 Desserts', '🌾 Vegan'],
    lookingForPreferred: ['🦞 Seafood', '🌮 World Cuisine', '🍔 Burgers & Street Food'],
  },
  {
    id: 'norwood-food-bazaar',
    name: 'Norwood Food Bazaar',
    category: 'Pop-up',
    suburb: 'Norwood', state: 'SA',
    location: 'The Parade, Norwood SA 5067',
    date: '2026-05-17',
    dateLabel: 'Sun 17 May 2026',
    dateLong: 'Sunday 17 May 2026',
    time: '10am–3pm', timeLong: '10:00am – 3:00pm',
    total: 10, filled: 9,
    feeMin: 100, feeMax: 180,
    deadline: '2026-05-03', deadlineLabel: '3 May 2026',
    stallSize: '2m × 2m or 3m × 2m',
    power: false, water: false,
    setupTime: '8:30am – 9:30am', packdown: '3:00pm – 4:00pm',
    attendance: '1,000–2,000 visitors',
    emoji: '⚡',
    about: 'The Norwood Food Bazaar is a curated pop-up food event on the iconic Parade, one of Adelaide\'s most beloved shopping and dining strips. With boutique retailers and cafes as neighbours, the Bazaar attracts an affluent, food-savvy crowd from the eastern suburbs and beyond. Only 10 vendor spots available — this intimate format means every vendor gets great visibility and genuine engagement with customers. Almost full — only 1 spot remaining.',
    organiser: { name: 'Norwood Payneham St Peters Council', initials: 'NP', events: 9, rating: 4.6 },
    vendorLineup: [
      { name: 'Napoli Express', type: 'Italian', initials: 'NE', id: 'napoli-express', color: '#C0392B' },
      { name: 'The Dessert Lab', type: 'Desserts', initials: 'DL', id: 'the-dessert-lab', color: '#C9840A' },
      { name: 'Beanery Coffee Co.', type: 'Coffee', initials: 'BC', id: 'beanery-coffee', color: '#2B5BA8' },
    ],
    feeIncludes: ['2×2m or 3×2m space', 'Event listing & signage', 'Shared waste facilities'],
    lookingFor: ['🍕 Italian & Mediterranean', '☕ Specialty Coffee', '🍰 Artisan Desserts', '🥗 Healthy & Fresh', '🌮 Gourmet Street Food'],
    lookingForPreferred: ['🍕 Italian & Mediterranean', '☕ Specialty Coffee', '🍰 Artisan Desserts'],
  },
  {
    id: 'victor-harbor-summer-fair',
    name: 'Victor Harbor Summer Fair',
    category: 'Festival',
    suburb: 'Victor Harbor', state: 'SA',
    location: 'Fleurieu Park, Esplanade, Victor Harbor SA 5211',
    date: '2026-05-24',
    dateLabel: 'Sun 24 May 2026',
    dateLong: 'Sunday 24 May 2026',
    time: '10am–4pm', timeLong: '10:00am – 4:00pm',
    total: 30, filled: 16,
    feeMin: 250, feeMax: 450,
    deadline: '2026-05-10', deadlineLabel: '10 May 2026',
    stallSize: '3m × 3m standard · 4m × 4m available',
    power: true, water: true,
    setupTime: '7:30am – 9:30am', packdown: '4:00pm – 6:00pm',
    attendance: '5,000–8,000 visitors',
    emoji: '🎡',
    about: 'The Victor Harbor Summer Fair is the Fleurieu Peninsula\'s biggest community event, drawing visitors from across South Australia to this charming seaside town. Set on the Esplanade with views of Granite Island and the famous horse-drawn tram, the fair features food, entertainment, and artisan markets in a stunning coastal setting. With 14 spots still available, this is a fantastic opportunity for vendors to reach a large, enthusiastic crowd in a destination event.',
    organiser: { name: 'Victor Harbor Council', initials: 'VH', events: 11, rating: 4.8 },
    vendorLineup: [
      { name: 'Ocean & Fire', type: 'Seafood', initials: 'OF', id: 'ocean-and-fire', color: '#2B5BA8' },
      { name: 'Brewski Burgers', type: 'Burgers', initials: 'BB', id: 'brewski-burgers', color: '#C9840A' },
      { name: 'Green Bowl', type: 'Vegan', initials: 'GB', id: 'green-bowl', color: '#2D8B55' },
    ],
    feeIncludes: ['3×3m or 4×4m stall space', 'Power & water access', 'Council event permit', 'Parking for vendor vehicles'],
    lookingFor: ['🦞 Seafood', '🌮 Street Food', '🎪 Festival Food', '🍔 Burgers', '☕ Coffee & Drinks', '🍦 Desserts', '🌾 Vegan & Healthy'],
    lookingForPreferred: ['🦞 Seafood', '🌮 Street Food', '🎪 Festival Food'],
  },
  {
    id: 'prospect-farmers-market',
    name: 'Prospect Farmers Market',
    category: 'Farmers Market',
    suburb: 'Prospect', state: 'SA',
    location: 'Prospect Oval, Gladstone Rd, Prospect SA 5082',
    date: '2026-05-31',
    dateLabel: 'Sun 31 May 2026',
    dateLong: 'Sunday 31 May 2026',
    time: '8am–12pm', timeLong: '8:00am – 12:00pm',
    total: 24, filled: 18,
    feeMin: 80, feeMax: 150,
    deadline: '2026-05-17', deadlineLabel: '17 May 2026',
    stallSize: '3m × 2m standard',
    power: false, water: true,
    setupTime: '6:30am – 7:30am', packdown: '12:00pm – 1:30pm',
    attendance: '1,500–2,500 visitors',
    emoji: '🌿',
    about: 'The Prospect Farmers Market is a grassroots Saturday institution in the inner northern suburbs, connecting local producers and food artisans directly with the community. The market prides itself on provenance — all food vendors must be able to demonstrate a local connection to their ingredients or production. A warm community atmosphere, loyal returning customers, and a growing reputation for quality make this one of Adelaide\'s most valued neighbourhood markets.',
    organiser: { name: 'City of Prospect', initials: 'CP', events: 28, rating: 4.6 },
    vendorLineup: [
      { name: 'Green Bowl', type: 'Vegan', initials: 'GB', id: 'green-bowl', color: '#2D8B55' },
      { name: 'Beanery Coffee Co.', type: 'Coffee', initials: 'BC', id: 'beanery-coffee', color: '#C9840A' },
      { name: 'Pressed & Brewed', type: 'Drinks', initials: 'PB', id: 'pressed-and-brewed', color: '#2B5BA8' },
    ],
    feeIncludes: ['3×2m stall space', 'Water access point', 'Shared waste facilities', 'Event signage'],
    lookingFor: ['🌿 Local Produce', '☕ Specialty Coffee', '🥞 Breakfast & Brunch', '🍞 Artisan Bakery', '🥗 Healthy & Vegan', '🍯 Preserves & Honey'],
    lookingForPreferred: ['🌿 Local Produce', '🥞 Breakfast & Brunch', '🍞 Artisan Bakery'],
  },
  {
    id: 'westpac-corporate-day',
    name: 'Westpac Corporate Food Day',
    category: 'Corporate',
    suburb: 'Adelaide CBD', state: 'SA',
    location: 'Westpac House Forecourt, 91 King William St, Adelaide SA 5000',
    date: '2026-06-07',
    dateLabel: 'Sun 7 Jun 2026',
    dateLong: 'Sunday 7 June 2026',
    time: '11am–2pm', timeLong: '11:00am – 2:00pm',
    total: 8, filled: 8,
    feeMin: 300, feeMax: 400,
    deadline: '2026-05-24', deadlineLabel: '24 May 2026',
    stallSize: '3m × 2m assigned',
    power: true, water: false,
    setupTime: '9:00am – 10:30am', packdown: '2:00pm – 3:30pm',
    attendance: '400–600 corporate attendees',
    emoji: '🏢',
    about: 'A private corporate lunch event hosted by Westpac for staff and clients at their Adelaide CBD headquarters. This curated, invite-only event offers 8 premium food vendors the opportunity to serve a professional, high-value audience in a controlled environment. All spots are now filled. Corporate events like this offer excellent pay, guaranteed foot traffic, and strong networking opportunities with organisers running repeat events throughout the year.',
    organiser: { name: 'Westpac Corporate Events', initials: 'WC', events: 6, rating: 5.0 },
    vendorLineup: [
      { name: "Smoky Joe's BBQ", type: 'BBQ & Grill', initials: 'SJ', id: 'smoky-joes-bbq', color: '#E8500A' },
      { name: 'Wok & Roll', type: 'Asian Fusion', initials: 'WR', id: 'wok-and-roll', color: '#2B5BA8' },
      { name: 'The Dessert Lab', type: 'Desserts', initials: 'DL', id: 'the-dessert-lab', color: '#C9840A' },
      { name: 'Beanery Coffee Co.', type: 'Coffee', initials: 'BC', id: 'beanery-coffee', color: '#2D8B55' },
    ],
    feeIncludes: ['Assigned 3×2m booth', '15A power', 'Staff-only event access', 'Catering coordination'],
    lookingFor: ['🥗 Healthy & Fresh', '🍱 Asian Cuisine', '☕ Specialty Coffee', '🧀 Gourmet', '🍦 Premium Desserts'],
    lookingForPreferred: ['🥗 Healthy & Fresh', '🍱 Asian Cuisine', '☕ Specialty Coffee'],
  },
  {
    id: 'henley-sunset-market',
    name: 'Henley Beach Sunset Market',
    category: 'Twilight Market',
    suburb: 'Henley Beach', state: 'SA',
    location: 'Henley Square, Henley Beach SA 5022',
    date: '2026-06-14',
    dateLabel: 'Sun 14 Jun 2026',
    dateLong: 'Sunday 14 June 2026',
    time: '4pm–8pm', timeLong: '4:00pm – 8:00pm',
    total: 16, filled: 6,
    feeMin: 120, feeMax: 200,
    deadline: '2026-05-31', deadlineLabel: '31 May 2026',
    stallSize: '3m × 3m standard',
    power: true, water: false,
    setupTime: '2:00pm – 3:30pm', packdown: '8:00pm – 9:30pm',
    attendance: '1,500–2,500 visitors',
    emoji: '🌅',
    about: 'Henley Square transforms at sunset into a vibrant twilight market, with golden hour over the beach providing a spectacular backdrop for this relaxed beachside event. The Henley Beach Sunset Market brings together food vendors, local artisans, and live musicians for an early-evening community celebration. With 10 spots still open, there\'s plenty of room for new vendors to join a growing event in one of Adelaide\'s most picturesque beachside precincts.',
    organiser: { name: 'City of Charles Sturt', initials: 'CS', events: 7, rating: 4.5 },
    vendorLineup: [
      { name: 'Ocean & Fire', type: 'Seafood', initials: 'OF', id: 'ocean-and-fire', color: '#2B5BA8' },
      { name: 'The Churro Stand', type: 'Desserts', initials: 'CH', id: 'the-churro-stand', color: '#C9840A' },
    ],
    feeIncludes: ['3×3m booth space', '15A power connection', 'Shared waste facilities', 'Event program listing'],
    lookingFor: ['🦞 Seafood', '🌮 Street Food', '🍦 Desserts', '☕ Coffee & Cold Drinks', '🌾 Vegan'],
    lookingForPreferred: ['🦞 Seafood', '🌮 Street Food', '🍦 Desserts'],
  },
  {
    id: 'marion-popup',
    name: 'Marion Shopping Centre Pop-up',
    category: 'Pop-up',
    suburb: 'Marion', state: 'SA',
    location: 'Westfield Marion, Diagonal Rd, Marion SA 5043',
    date: '2026-06-21',
    dateLabel: 'Sun 21 Jun 2026',
    dateLong: 'Sunday 21 June 2026',
    time: '10am–4pm', timeLong: '10:00am – 4:00pm',
    total: 12, filled: 10,
    feeMin: 200, feeMax: 350,
    deadline: '2026-06-07', deadlineLabel: '7 June 2026',
    stallSize: '2m × 2m or 3m × 2m',
    power: true, water: false,
    setupTime: '8:30am – 9:30am', packdown: '4:00pm – 5:30pm',
    attendance: '6,000–10,000 shoppers',
    emoji: '🛍️',
    about: 'A premium indoor pop-up market inside Westfield Marion, one of South Australia\'s largest shopping centres. This event offers vendors access to massive foot traffic in a climate-controlled environment — perfect for winter months. Positioned in the centre atrium, the food vendors complement the existing food court offering, catching shoppers at peak lunch and afternoon traffic. Only 2 spots remaining — apply early.',
    organiser: { name: 'Westfield Marion Events', initials: 'WM', events: 14, rating: 4.4 },
    vendorLineup: [
      { name: 'Taco Loco', type: 'Mexican', initials: 'TL', id: 'taco-loco', color: '#2D8B55' },
      { name: 'The Dessert Lab', type: 'Desserts', initials: 'DL', id: 'the-dessert-lab', color: '#C9840A' },
      { name: 'Napoli Express', type: 'Italian', initials: 'NE', id: 'napoli-express', color: '#C0392B' },
      { name: 'Beanery Coffee Co.', type: 'Coffee', initials: 'BC', id: 'beanery-coffee', color: '#2B5BA8' },
    ],
    feeIncludes: ['Assigned indoor booth space', '15A power', 'Westfield marketing inclusion', 'Climate-controlled environment'],
    lookingFor: ['🌮 Gourmet Street Food', '🍰 Desserts & Treats', '☕ Coffee & Drinks', '🍕 Pizza & Italian', '🥗 Healthy & Fresh'],
    lookingForPreferred: ['🌮 Gourmet Street Food', '🍰 Desserts & Treats', '☕ Coffee & Drinks'],
  },
];

window.PITCH_VENDORS = [
  {
    id: 'smoky-joes-bbq',
    name: "Smoky Joe's BBQ",
    cuisines: ['BBQ', 'Ribs', 'Brisket'],
    setup: 'Food Truck',
    suburb: 'Norwood', state: 'SA',
    rating: 4.9, reviews: 62, events: 47,
    isPro: true,
    emoji: '🔥',
    bg: 'linear-gradient(135deg,#2D1A0A 0%,#5C2A08 100%)',
    bio: "Adelaide's most-loved BBQ food truck, smoking low-and-slow since 2019. We specialise in American-style pit BBQ — brisket, baby back ribs, and pulled pork rolls — all slow-cooked over ironbark wood for 12–16 hours. We've been a fixture at Rundle Mall Night Eats for three consecutive years and have served over 28,000 people at events across South Australia. Our compact 3×3m setup requires single-phase power and we're known for our punctual pack-down.",
    priceRange: '$12–$22',
    stallW: 3, stallD: 3,
    power: true, water: false,
    instagram: '@smokyjoes_adl',
    gallery: [
      { emoji: '🔥', bg: 'linear-gradient(135deg,#3D1A06,#6B2E08)', caption: 'Our custom smoker at work' },
      { emoji: '🥩', bg: 'linear-gradient(135deg,#2D1A0A,#4A2808)', caption: '12-hour brisket, ready to slice' },
      { emoji: '🍖', bg: 'linear-gradient(135deg,#1A1208,#382208)', caption: 'Baby back ribs — crowd favourite' },
      { emoji: '🥪', bg: 'linear-gradient(135deg,#2A1006,#521E08)', caption: 'Pulled pork roll with house slaw' },
      { emoji: '🌽', bg: 'linear-gradient(135deg,#1E1208,#3C2208)', caption: 'Smoky corn cob side' },
    ],
    pastEvents: [
      { name: 'Rundle Mall Night Eats', id: 'rundle-mall-night-eats', date: 'Apr 2026' },
      { name: 'Adelaide Showground Harvest Fair', id: 'showground-harvest-fair', date: 'Apr 2026' },
      { name: 'Fringe Food Village 2026', id: 'fringe-food-village', date: 'Mar 2026' },
      { name: 'Glenelg Twilight Market', id: 'glenelg-twilight', date: 'Feb 2026' },
      { name: 'Barossa Valley Food & Wine', id: 'barossa-food-wine', date: 'Jan 2026' },
      { name: 'Port Adelaide Night Market', id: 'port-adelaide-night-market', date: 'Jan 2026' },
      { name: 'Norwood Food Bazaar', id: 'norwood-food-bazaar', date: 'Dec 2025' },
    ],
    reviewsList: [
      { org: 'Adelaide City Council Events', event: 'Rundle Mall Night Eats · Apr 2026', rating: 5, text: "Smoky Joe's were absolutely outstanding — arrived early, set up efficiently with zero fuss, and the queue at their stall was consistently the longest all night. Food quality was exceptional and they were professional throughout pack-down. Already confirmed for our next three events." },
      { org: 'Glenelg Foreshore Markets', event: 'Glenelg Twilight Market · May 2026', rating: 5, text: "Best BBQ truck we've had at any of our events. Crowd loved them. Reliable, clean, incredibly professional. The smell alone brought people across the market." },
      { org: 'Adelaide Fringe Festival', event: 'Fringe Food Village 2026 · Mar 2026', rating: 5, text: "Consistent five-star vendor across all 21 nights of the festival. Never a complaint, always smiling. Their pulled pork roll became legendary by week 2." },
    ],
  },
  {
    id: 'taco-loco',
    name: 'Taco Loco',
    cuisines: ['Mexican', 'Tacos', 'Burritos'],
    setup: 'Pop-up Stall',
    suburb: 'Glenelg', state: 'SA',
    rating: 4.7, reviews: 38, events: 23,
    isPro: true,
    emoji: '🌮',
    bg: 'linear-gradient(135deg,#1A2D0A 0%,#2D5C10 100%)',
    bio: "Authentic Mexican street food made from scratch every day. Our family recipes come straight from Oaxaca — hand-pressed tortillas, slow-braised meats, and house-made salsas ranging from mild to face-meltingly hot. We're a 3×2m pop-up stall that's punched well above our weight at every market we've attended. Our al pastor and fish tacos have won back-to-back 'best bite' awards at Adelaide Fringe.",
    priceRange: '$8–$16',
    stallW: 3, stallD: 2,
    power: false, water: true,
    instagram: '@tacoloco_glenelg',
    gallery: [
      { emoji: '🌮', bg: 'linear-gradient(135deg,#1A2D0A,#2D5C10)', caption: 'Al pastor tacos — our signature' },
      { emoji: '🌯', bg: 'linear-gradient(135deg,#152206,#2A4A0C)', caption: 'Burrito bowl with all the toppings' },
      { emoji: '🍅', bg: 'linear-gradient(135deg,#2A1A08,#4A3010)', caption: 'House-made salsa verde & roja' },
      { emoji: '🫔', bg: 'linear-gradient(135deg,#1A2008,#303818)', caption: 'Hand-pressed corn tortillas' },
      { emoji: '🌶️', bg: 'linear-gradient(135deg,#2A0808,#500E0E)', caption: 'Chilli selection — choose your heat' },
    ],
    pastEvents: [
      { name: 'Fringe Food Village 2026', id: 'fringe-food-village', date: 'Mar 2026' },
      { name: 'Glenelg Twilight Market', id: 'glenelg-twilight', date: 'Feb 2026' },
      { name: 'Marion Shopping Centre Pop-up', id: 'marion-popup', date: 'Jan 2026' },
      { name: 'Rundle Mall Night Eats', id: 'rundle-mall-night-eats', date: 'Dec 2025' },
    ],
    reviewsList: [
      { org: 'Adelaide Fringe Festival', event: 'Fringe Food Village 2026 · Mar 2026', rating: 5, text: "Taco Loco was the standout food stall of the entire festival. Their al pastor tacos had a queue from 5pm to close every single night. Couldn't recommend them more highly." },
      { org: 'City of Holdfast Bay', event: 'Glenelg Twilight Market · Feb 2026', rating: 5, text: "A crowd favourite every time they come back. Professional, fast service, and the food is genuinely exceptional. Our market regulars always ask when they're returning." },
      { org: 'Westfield Marion Events', event: 'Marion Pop-up · Jan 2026', rating: 4, text: "Great stall, very popular. Setup was a little slow but once they got going the service was fast and the food quality was top notch." },
    ],
  },
  {
    id: 'wok-and-roll',
    name: 'Wok & Roll',
    cuisines: ['Asian Fusion', 'Noodles', 'Bao'],
    setup: 'Food Truck',
    suburb: 'Adelaide CBD', state: 'SA',
    rating: 4.8, reviews: 51, events: 31,
    isPro: true,
    emoji: '🥢',
    bg: 'linear-gradient(135deg,#0A1A2D 0%,#0A3060 100%)',
    bio: "A modern Asian fusion food truck serving bold, wok-fired flavours inspired by street food from Japan, Korea, Thailand, and Vietnam. Our signature dishes — kimchi fried rice, pad see ew noodles, and teriyaki chicken bao — are made to order from our custom fit-out truck. We're fully self-contained with our own water and generator, making us suitable for any event regardless of infrastructure.",
    priceRange: '$10–$18',
    stallW: 3, stallD: 6,
    power: false, water: false,
    instagram: '@wokandroll_adl',
    gallery: [
      { emoji: '🥢', bg: 'linear-gradient(135deg,#0A1A2D,#0A3060)', caption: 'Wok-fired noodles to order' },
      { emoji: '🍱', bg: 'linear-gradient(135deg,#0A1420,#082040)', caption: 'Our bento box sets' },
      { emoji: '🥟', bg: 'linear-gradient(135deg,#0C1828,#0A2850)', caption: 'Pan-fried gyoza — 6 per serve' },
      { emoji: '🍜', bg: 'linear-gradient(135deg,#081220,#082848)', caption: 'Ramen broth — slow-simmered 8 hours' },
      { emoji: '🧆', bg: 'linear-gradient(135deg,#0A1628,#0A2C58)', caption: 'Korean fried chicken bao' },
    ],
    pastEvents: [
      { name: 'Rundle Mall Night Eats', id: 'rundle-mall-night-eats', date: 'Apr 2026' },
      { name: 'Fringe Food Village 2026', id: 'fringe-food-village', date: 'Mar 2026' },
      { name: 'Westpac Corporate Food Day', id: 'westpac-corporate-day', date: 'Jun 2026' },
      { name: 'Barossa Valley Food & Wine', id: 'barossa-food-wine', date: 'Apr 2026' },
    ],
    reviewsList: [
      { org: 'Adelaide City Council Events', event: 'Rundle Mall Night Eats · Apr 2026', rating: 5, text: "Wok & Roll always draw a consistent queue. Their self-contained setup means zero headaches for us as organisers, and the quality of their food is exceptional. One of our most-requested vendors." },
      { org: 'Westpac Corporate Events', event: 'Westpac Corporate Day · Jun 2026', rating: 5, text: "Absolutely ideal for a corporate setting. Minimal mess, quick service, and the food suits every palate. Will definitely be booking again." },
    ],
  },
  {
    id: 'napoli-express',
    name: 'Napoli Express',
    cuisines: ['Italian', 'Pizza', 'Arancini'],
    setup: 'Pop-up Stall',
    suburb: 'Hindmarsh', state: 'SA',
    rating: 4.6, reviews: 29, events: 19,
    isPro: false,
    emoji: '🍕',
    bg: 'linear-gradient(135deg,#2D0A0A 0%,#601818 100%)',
    bio: "Authentic Neapolitan-style pizza, calzones, and arancini made fresh on-site. Our dough is cold-proofed for 72 hours and cooked in our portable wood-fired oven (gas-assist) reaching 450°C for a genuine Neapolitan char. Based in Hindmarsh, we've grown from a weekend stall into a full-time events business over three years. We're known for our quick service without sacrificing quality — 90-second cook time means even peak queues move fast.",
    priceRange: '$12–$20',
    stallW: 4, stallD: 3,
    power: true, water: true,
    instagram: '@napoliexpressadl',
    gallery: [
      { emoji: '🍕', bg: 'linear-gradient(135deg,#2D0A0A,#601818)', caption: 'Margherita from our wood-fired oven' },
      { emoji: '🫕', bg: 'linear-gradient(135deg,#250808,#500E0E)', caption: 'Arancini — made fresh each morning' },
      { emoji: '🥖', bg: 'linear-gradient(135deg,#2A0C0C,#581414)', caption: 'Focaccia with rosemary & sea salt' },
      { emoji: '🍅', bg: 'linear-gradient(135deg,#200808,#440C0C)', caption: 'House-made San Marzano sauce' },
    ],
    pastEvents: [
      { name: 'Norwood Food Bazaar', id: 'norwood-food-bazaar', date: 'May 2026' },
      { name: 'Marion Shopping Centre Pop-up', id: 'marion-popup', date: 'Jun 2026' },
      { name: 'Barossa Valley Food & Wine', id: 'barossa-food-wine', date: 'Apr 2026' },
    ],
    reviewsList: [
      { org: 'Norwood Payneham St Peters Council', event: 'Norwood Food Bazaar · May 2026', rating: 5, text: "The smell of that wood-fired oven drew people across the entire market. Napoli Express was incredibly well-received and their queue never dropped below 10 people the whole day." },
      { org: 'Barossa Valley Tourism', event: 'Barossa Food & Wine · Apr 2026', rating: 4, text: "Great quality pizza, very authentic. Setup took a little longer than anticipated due to the oven, but once running it was smooth and the product was exceptional." },
    ],
  },
  {
    id: 'the-dessert-lab',
    name: 'The Dessert Lab',
    cuisines: ['Desserts', 'Ice Cream', 'Pastry'],
    setup: 'Cart',
    suburb: 'North Adelaide', state: 'SA',
    rating: 4.9, reviews: 44, events: 28,
    isPro: true,
    emoji: '🍰',
    bg: 'linear-gradient(135deg,#2D1A2A 0%,#5C2A52 100%)',
    bio: "A creative dessert cart serving handcrafted sweets that blur the line between pastry chef and street food. Our menu rotates seasonally and has included liquid nitrogen ice cream, burnt Basque cheesecake, crème brûlée doughnuts, and mochi waffle sandwiches. We're compact (2×2m cart), require only a power point, and consistently generate the most social media content of any vendor at an event. Instagram-worthy by design.",
    priceRange: '$7–$14',
    stallW: 2, stallD: 2,
    power: true, water: false,
    instagram: '@thedessertlab',
    gallery: [
      { emoji: '🍰', bg: 'linear-gradient(135deg,#2D1A2A,#5C2A52)', caption: 'Burnt Basque cheesecake' },
      { emoji: '🍩', bg: 'linear-gradient(135deg,#251628,#4A2248)', caption: 'Crème brûlée doughnut' },
      { emoji: '🧁', bg: 'linear-gradient(135deg,#2A1825,#521E40)', caption: 'Seasonal signature cupcake' },
      { emoji: '🍨', bg: 'linear-gradient(135deg,#201220,#3C1A3A)', caption: 'Liquid nitrogen ice cream — live made' },
    ],
    pastEvents: [
      { name: 'Fringe Food Village 2026', id: 'fringe-food-village', date: 'Mar 2026' },
      { name: 'Barossa Valley Food & Wine', id: 'barossa-food-wine', date: 'Apr 2026' },
      { name: 'Westpac Corporate Food Day', id: 'westpac-corporate-day', date: 'Jun 2026' },
      { name: 'Norwood Food Bazaar', id: 'norwood-food-bazaar', date: 'May 2026' },
      { name: 'Marion Shopping Centre Pop-up', id: 'marion-popup', date: 'Jun 2026' },
    ],
    reviewsList: [
      { org: 'Adelaide Fringe Festival', event: 'Fringe Food Village 2026 · Mar 2026', rating: 5, text: "Every single night we watched people photograph their desserts before eating them. The Dessert Lab is a social media machine — and the food is just as good as it looks. Phenomenal vendor." },
      { org: 'Westpac Corporate Events', event: 'Westpac Corporate Day · Jun 2026', rating: 5, text: "The liquid nitrogen ice cream was the talk of the entire event. Guests were genuinely delighted. We'll be booking The Dessert Lab for every corporate event going forward." },
    ],
  },
  {
    id: 'beanery-coffee',
    name: 'Beanery Coffee Co.',
    cuisines: ['Coffee & Drinks', 'Cold Brew', 'Matcha'],
    setup: 'Cart',
    suburb: 'Unley', state: 'SA',
    rating: 4.7, reviews: 33, events: 35,
    isPro: false,
    emoji: '☕',
    bg: 'linear-gradient(135deg,#1A140A 0%,#3D2A10 100%)',
    bio: "Specialty coffee on wheels. We source single-origin beans from across Australia and serve them through a modified La Marzocco espresso machine mounted on our custom cart. Beyond espresso, we offer cold brew, matcha lattes, and a rotating seasonal drink menu. We're the favourite support vendor for early-morning markets and corporate events — arriving early, staying late, and keeping organisers caffeinated throughout setup.",
    priceRange: '$4.50–$8',
    stallW: 2, stallD: 1.5,
    power: true, water: true,
    instagram: '@beanery_coffee',
    gallery: [
      { emoji: '☕', bg: 'linear-gradient(135deg,#1A140A,#3D2A10)', caption: 'Single-origin espresso' },
      { emoji: '🧊', bg: 'linear-gradient(135deg,#141008,#2E2010)', caption: 'Cold brew — 24-hour steep' },
      { emoji: '🍵', bg: 'linear-gradient(135deg,#181208,#342208)', caption: 'Ceremonial matcha latte' },
      { emoji: '🥛', bg: 'linear-gradient(135deg,#201A10,#3A2C14)', caption: 'Our La Marzocco cart setup' },
    ],
    pastEvents: [
      { name: 'Rundle Mall Night Eats', id: 'rundle-mall-night-eats', date: 'Apr 2026' },
      { name: 'Adelaide Showground Harvest Fair', id: 'showground-harvest-fair', date: 'Apr 2026' },
      { name: 'Glenelg Twilight Market', id: 'glenelg-twilight', date: 'May 2026' },
      { name: 'Norwood Food Bazaar', id: 'norwood-food-bazaar', date: 'May 2026' },
      { name: 'Westpac Corporate Food Day', id: 'westpac-corporate-day', date: 'Jun 2026' },
      { name: 'Marion Shopping Centre Pop-up', id: 'marion-popup', date: 'Jun 2026' },
    ],
    reviewsList: [
      { org: 'SA Showground Events', event: 'Harvest Fair · Apr 2026', rating: 5, text: "Beanery Coffee is our first call for every morning event. They arrive before anyone else, make incredible coffee, and keep the energy high. Genuinely indispensable." },
      { org: 'Norwood Payneham St Peters Council', event: 'Norwood Food Bazaar · May 2026', rating: 5, text: "Best coffee at any market we've run. The queue was constant all morning. Their seasonal latte was the most Instagrammed thing at the whole event." },
    ],
  },
  {
    id: 'green-bowl',
    name: 'Green Bowl',
    cuisines: ['Vegan', 'Plant-Based', 'Bowls'],
    setup: 'Pop-up Stall',
    suburb: 'Prospect', state: 'SA',
    rating: 4.5, reviews: 17, events: 14,
    isPro: false,
    emoji: '🥗',
    bg: 'linear-gradient(135deg,#0A2010 0%,#144A22 100%)',
    bio: "Wholesome, colourful vegan and plant-based street food that actually tastes incredible. Our bowls are built around seasonal SA vegetables, house-made dressings, and whole-grain bases — designed to be filling, nutritious, and genuinely delicious for vegans and meat-eaters alike. We started at the Prospect Farmers Market in 2023 and have steadily grown our event presence. Everything is made fresh on-site, with zero single-use plastics in our packaging.",
    priceRange: '$12–$18',
    stallW: 3, stallD: 2,
    power: false, water: true,
    instagram: '@greenbowl_sa',
    gallery: [
      { emoji: '🥗', bg: 'linear-gradient(135deg,#0A2010,#144A22)', caption: 'Seasonal grain bowl — Tuesday special' },
      { emoji: '🥑', bg: 'linear-gradient(135deg,#081A0C,#103C1A)', caption: 'Smashed avo toast with dukkah' },
      { emoji: '🌽', bg: 'linear-gradient(135deg,#0A1E0E,#124422)', caption: 'Mexican-inspired corn & bean bowl' },
      { emoji: '🍠', bg: 'linear-gradient(135deg,#0C2214,#16502C)', caption: 'Roast sweet potato & tahini' },
    ],
    pastEvents: [
      { name: 'Adelaide Showground Harvest Fair', id: 'showground-harvest-fair', date: 'Apr 2026' },
      { name: 'Prospect Farmers Market', id: 'prospect-farmers-market', date: 'May 2026' },
      { name: 'Glenelg Twilight Market', id: 'glenelg-twilight', date: 'Mar 2026' },
      { name: 'Victor Harbor Summer Fair', id: 'victor-harbor-summer-fair', date: 'May 2026' },
    ],
    reviewsList: [
      { org: 'City of Prospect', event: 'Prospect Farmers Market · May 2026', rating: 5, text: "Green Bowl is a market staple and genuinely one of the most popular stalls we have. Their packaging is fully compostable and their commitment to sustainability aligns perfectly with our market values." },
      { org: 'SA Showground Events', event: 'Harvest Fair · Apr 2026', rating: 4, text: "Really popular with the health-conscious crowd. Food was delicious and portions were generous. A little slow during peak rush but quality more than made up for it." },
    ],
  },
  {
    id: 'brewski-burgers',
    name: 'Brewski Burgers',
    cuisines: ['Burgers', 'Smash Burgers', 'Fries'],
    setup: 'Food Truck',
    suburb: 'Port Adelaide', state: 'SA',
    rating: 4.6, reviews: 26, events: 22,
    isPro: false,
    emoji: '🍔',
    bg: 'linear-gradient(135deg,#1E1408 0%,#4A2C0C 100%)',
    bio: "Port Adelaide's premier burger truck, serving smash burgers and thick-cut fries from a purpose-built truck. Our beef is sourced from a single SA family farm — dry-aged and freshly ground daily. Our signature Brewski Burger stacks a double smash patty with aged cheddar, pickles, and our house sauce on a toasted brioche bun. We also do a killer vegan patty option. Built for speed — we can hit 120+ serves per hour during peak.",
    priceRange: '$12–$22',
    stallW: 3, stallD: 6,
    power: false, water: false,
    instagram: '@brewski_burgers',
    gallery: [
      { emoji: '🍔', bg: 'linear-gradient(135deg,#1E1408,#4A2C0C)', caption: 'The Brewski — double smash, double cheddar' },
      { emoji: '🍟', bg: 'linear-gradient(135deg,#181008,#3C2408)', caption: 'Seasoned thick-cut fries' },
      { emoji: '🥩', bg: 'linear-gradient(135deg,#1A0E06,#3A2008)', caption: 'SA farm beef, fresh-ground daily' },
      { emoji: '🧀', bg: 'linear-gradient(135deg,#201408,#462A10)', caption: 'Aged cheddar sauce — our house recipe' },
    ],
    pastEvents: [
      { name: 'Port Adelaide Night Market', id: 'port-adelaide-night-market', date: 'May 2026' },
      { name: 'Victor Harbor Summer Fair', id: 'victor-harbor-summer-fair', date: 'May 2026' },
      { name: 'Fringe Food Village 2026', id: 'fringe-food-village', date: 'Mar 2026' },
    ],
    reviewsList: [
      { org: 'Port Adelaide Enfield Council', event: 'Port Adelaide Night Market · May 2026', rating: 5, text: "Brewski Burgers are everything you want in a night market food truck. Fast, consistent, and the product is genuinely excellent. Their Port Adelaide roots resonate with our local crowd." },
      { org: 'Victor Harbor Council', event: 'Victor Harbor Summer Fair · May 2026', rating: 4, text: "Very popular, especially with the families. The vegan burger option was a great addition. Efficient service even when the queue was 30+ people deep." },
    ],
  },
  {
    id: 'ocean-and-fire',
    name: 'Ocean & Fire',
    cuisines: ['Seafood', 'Grilled Fish', 'Oysters'],
    setup: 'Pop-up Stall',
    suburb: 'Glenelg', state: 'SA',
    rating: 4.8, reviews: 22, events: 17,
    isPro: true,
    emoji: '🦞',
    bg: 'linear-gradient(135deg,#0A1A2A 0%,#0A3050 100%)',
    bio: "Premium seafood on the street. Ocean & Fire sources directly from SA fishermen — prawns off the Gulf, King George whiting from the Spencer Gulf, and farmed Coffin Bay oysters. We grill, fry, and serve with precision, offering a restaurant-quality seafood experience at street food prices. Perfect for coastal events and premium markets. Pro-certified and operating with full seafood handler accreditation.",
    priceRange: '$14–$28',
    stallW: 3, stallD: 3,
    power: true, water: true,
    instagram: '@oceanandfire_sa',
    gallery: [
      { emoji: '🦞', bg: 'linear-gradient(135deg,#0A1A2A,#0A3050)', caption: 'Moreton Bay bugs on the grill' },
      { emoji: '🦐', bg: 'linear-gradient(135deg,#081620,#083040)', caption: 'Gulf prawns — market fresh' },
      { emoji: '🐟', bg: 'linear-gradient(135deg,#0A1828,#0A2E4A)', caption: 'King George whiting, lemon & herb' },
      { emoji: '🦪', bg: 'linear-gradient(135deg,#08141E,#082840)', caption: 'Coffin Bay oysters on the half shell' },
    ],
    pastEvents: [
      { name: 'Glenelg Twilight Market', id: 'glenelg-twilight', date: 'May 2026' },
      { name: 'Victor Harbor Summer Fair', id: 'victor-harbor-summer-fair', date: 'May 2026' },
      { name: 'Barossa Valley Food & Wine', id: 'barossa-food-wine', date: 'Apr 2026' },
      { name: 'Henley Beach Sunset Market', id: 'henley-sunset-market', date: 'Jun 2026' },
    ],
    reviewsList: [
      { org: 'City of Holdfast Bay', event: 'Glenelg Twilight Market · May 2026', rating: 5, text: "Ocean & Fire are the perfect coastal event vendor. Immaculate presentation, genuinely fresh seafood, and a crowd-drawing setup. We've had organisers from other councils ask us how we got them." },
      { org: 'Barossa Valley Tourism', event: 'Barossa Food & Wine · Apr 2026', rating: 5, text: "A revelation at a wine and food event. The Coffin Bay oysters paired with local whites created something genuinely special. Extremely professional and well-presented." },
    ],
  },
  {
    id: 'the-churro-stand',
    name: 'The Churro Stand',
    cuisines: ['Desserts', 'Churros', 'Spanish'],
    setup: 'Cart',
    suburb: 'Adelaide CBD', state: 'SA',
    rating: 4.4, reviews: 14, events: 11,
    isPro: false,
    emoji: '🍩',
    bg: 'linear-gradient(135deg,#2A1A08 0%,#604010 100%)',
    bio: "Hot, fresh churros with a dozen dipping sauces and creative toppings. Our cart is simple, compact, and produces an irresistible smell that draws crowds from 50 metres away. Classic cinnamon sugar churros alongside specials like Nutella-filled, dulce de leche, and seasonal creations. Fast-casual format, low setup overhead, and a product that never fails to sell. Great choice for family events and twilight markets.",
    priceRange: '$6–$12',
    stallW: 2, stallD: 1.5,
    power: true, water: false,
    instagram: '@thechurrostand',
    gallery: [
      { emoji: '🍩', bg: 'linear-gradient(135deg,#2A1A08,#604010)', caption: 'Classic cinnamon churros' },
      { emoji: '🍫', bg: 'linear-gradient(135deg,#22140A,#502E0A)', caption: 'Nutella-dipped churro bites' },
      { emoji: '🌰', bg: 'linear-gradient(135deg,#241606,#4A2C08)', caption: 'Dulce de leche drizzle' },
    ],
    pastEvents: [
      { name: 'Glenelg Twilight Market', id: 'glenelg-twilight', date: 'Mar 2026' },
      { name: 'Henley Beach Sunset Market', id: 'henley-sunset-market', date: 'Jun 2026' },
      { name: 'Rundle Mall Night Eats', id: 'rundle-mall-night-eats', date: 'Feb 2026' },
    ],
    reviewsList: [
      { org: 'City of Holdfast Bay', event: 'Glenelg Twilight Market · Mar 2026', rating: 4, text: "The Churro Stand is a crowd pleaser, full stop. Families loved it, and the smell alone brought people over. Quick and friendly service throughout the evening." },
      { org: 'City of Charles Sturt', event: 'Henley Beach Sunset Market · Jun 2026', rating: 5, text: "Simple concept, executed perfectly. The Churro Stand has been one of our most popular vendors two events running. Kids and adults alike — they appeal to everyone." },
    ],
  },
  {
    id: 'punjab-palace',
    name: 'Punjab Palace',
    cuisines: ['Indian', 'Curry', 'Tandoor'],
    setup: 'Food Truck',
    suburb: 'Elizabeth', state: 'SA',
    rating: 4.7, reviews: 31, events: 26,
    isPro: false,
    emoji: '🍛',
    bg: 'linear-gradient(135deg,#2A1A00 0%,#5A3600 100%)',
    bio: "Authentic Punjabi cooking from a food truck that smells like a dhaba and tastes even better. Our family-run operation brings recipes perfected over three generations — slow-cooked curries, fresh-baked naan from a tandoor oven mounted in the truck, butter chicken that's become famous in Adelaide's food truck scene, and fragrant biryanis made in 5kg batches. We serve substantial portions at generous prices and always have a vegetarian and vegan option.",
    priceRange: '$10–$18',
    stallW: 3, stallD: 5,
    power: false, water: false,
    instagram: '@punjabpalace_adl',
    gallery: [
      { emoji: '🍛', bg: 'linear-gradient(135deg,#2A1A00,#5A3600)', caption: 'Butter chicken — 4-hour slow cook' },
      { emoji: '🫓', bg: 'linear-gradient(135deg,#241600,#4A2C00)', caption: 'Fresh naan from our tandoor' },
      { emoji: '🍲', bg: 'linear-gradient(135deg,#281800,#523200)', caption: 'Lamb biryani — fragrant basmati' },
      { emoji: '🌿', bg: 'linear-gradient(135deg,#201400,#402A00)', caption: 'Dal makhani — vegan favourite' },
    ],
    pastEvents: [
      { name: 'Port Adelaide Night Market', id: 'port-adelaide-night-market', date: 'May 2026' },
      { name: 'Fringe Food Village 2026', id: 'fringe-food-village', date: 'Mar 2026' },
      { name: 'Victor Harbor Summer Fair', id: 'victor-harbor-summer-fair', date: 'May 2026' },
    ],
    reviewsList: [
      { org: 'Adelaide Fringe Festival', event: 'Fringe Food Village 2026 · Mar 2026', rating: 5, text: "The smell of Punjab Palace's tandoor drew people from across the park. Their butter chicken consistently sold out before closing. A genuinely brilliant addition to any food event." },
      { org: 'Port Adelaide Enfield Council', event: 'Port Adelaide Night Market · May 2026', rating: 5, text: "One of the most popular vendors at Port Adelaide. The freshly baked naan is something else — people were coming back for seconds. Excellent, warm-hearted team." },
    ],
  },
  {
    id: 'pressed-and-brewed',
    name: 'Pressed & Brewed',
    cuisines: ['Coffee & Drinks', 'Juices', 'Herbal'],
    setup: 'Cart',
    suburb: 'Burnside', state: 'SA',
    rating: 4.5, reviews: 12, events: 9,
    isPro: false,
    emoji: '🍵',
    bg: 'linear-gradient(135deg,#0E1A0E 0%,#1C3A1A 100%)',
    bio: "A compact drinks cart specialising in cold-pressed juices, herbal infusions, and filter coffee. All juices are pressed fresh on-site from whole SA fruit and vegetables — no concentrates, no additives. Our filter coffee uses a rotating single-origin roast from a different Australian roaster each month. Ideal for health-conscious markets, morning events, and as a complementary beverage option alongside food vendors. Small footprint, quick service.",
    priceRange: '$5–$10',
    stallW: 1.5, stallD: 1.5,
    power: true, water: true,
    instagram: '@pressedandbrewed',
    gallery: [
      { emoji: '🍵', bg: 'linear-gradient(135deg,#0E1A0E,#1C3A1A)', caption: 'Herbal infusion — rotating seasonal' },
      { emoji: '🧃', bg: 'linear-gradient(135deg,#0C1808,#183215)', caption: 'Cold-pressed green juice — pressed fresh' },
      { emoji: '☕', bg: 'linear-gradient(135deg,#101C10,#1E3C1C)', caption: 'Filter coffee — single origin monthly' },
    ],
    pastEvents: [
      { name: 'Adelaide Showground Harvest Fair', id: 'showground-harvest-fair', date: 'Apr 2026' },
      { name: 'Prospect Farmers Market', id: 'prospect-farmers-market', date: 'May 2026' },
      { name: 'Norwood Food Bazaar', id: 'norwood-food-bazaar', date: 'May 2026' },
    ],
    reviewsList: [
      { org: 'City of Prospect', event: 'Prospect Farmers Market · May 2026', rating: 5, text: "Pressed & Brewed is exactly the kind of vendor our market was missing. Their product is impeccable, their setup immaculate, and the cold-press juices are a revelation." },
      { org: 'SA Showground Events', event: 'Harvest Fair · Apr 2026', rating: 4, text: "A great complementary addition to the market. Very popular with health-conscious attendees. The fresh juice line was a nice differentiator from the coffee-heavy vendor lineup." },
    ],
  },
];
